[package]
name = "rpc-testclient"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = "^1.14.1"
solana-sdk = "^1.14.0"
serde_json = "1.0.83"
